import 'package:bugsee_flutter/bugsee_flutter.dart';

AndroidLaunchOptions androidLaunchOptions = AndroidLaunchOptions()
  ..captureDeviceAndNetworkNames = false
  ..captureLogs = false
  ..crashReport = false
  ..defaultBugPriority = BugseeSeverityLevel.blocker
  ..defaultCrashPriority = BugseeSeverityLevel.critical
  ..frameRate = BugseeFrameRate.low
  ..maxDataSize = 20
  ..maxNetworkBodySize = 20
  ..maxRecordingTime = 20
  ..monitorNetwork = false
  ..notificationBarTrigger = false
  ..reportDescriptionRequired = false
  ..reportEmailRequired = false
  ..reportLabelsEnabled = false
  ..reportLabelsRequired = false
  ..reportPrioritySelector = false
  ..reportSummaryRequired = false
  ..screenshotEnabled = false
  ..serviceMode = false
  ..shakeToReport = false
  ..videoEnabled = false
  ..videoMode = BugseeVideoMode.v1
  ..videoQuality = BugseeVideoQuality.defaultQuality
  ..videoScale = 0.5
  ..viewHierarchyEnabled = false
  ..wifiOnlyUpload = true;

IOSLaunchOptions iOSLaunchOptions = IOSLaunchOptions()
  ..captureDeviceAndNetworkNames = false
  ..captureLogs = false
  ..crashReport = false
  ..defaultBugPriority = BugseeSeverityLevel.blocker
  ..defaultCrashPriority = BugseeSeverityLevel.critical
  ..frameRate = BugseeFrameRate.low
  ..maxDataSize = 20
  ..maxNetworkBodySize = 20
  ..maxRecordingTime = 20
  ..monitorNetwork = false
  ..reportDescriptionRequired = false
  ..reportEmailRequired = false
  ..reportLabelsEnabled = false
  ..reportLabelsRequired = false
  ..reportPrioritySelector = false
  ..reportSummaryRequired = false
  ..screenshotEnabled = false
  ..shakeToReport = false
  ..videoEnabled = false
  ..videoScale = 0.5
  ..viewHierarchyEnabled = false
  ..wifiOnlyUpload = true;
