// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// According to firebase documentation Firebase API Keys are not secrets. https://firebase.google.com/docs/projects/api-keys
  /// Because of that it's ok to expose Firebase API keys in code.
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANX3fUUu7K6-dCpfLLYkKvalzHaIUQXCE',
    appId: '1:139514080243:web:1fc151a0dc66e448f0c086',
    messagingSenderId: '139514080243',
    projectId: 'flutterapplicationtempla-79caa',
    authDomain: 'flutterapplicationtempla-79caa.firebaseapp.com',
    storageBucket: 'flutterapplicationtempla-79caa.appspot.com',
    measurementId: 'G-617W5ZKC96',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE4ib2TgIR4bkBzKr7iiKgK4i7zHQek4E',
    appId: '1:247344237480:android:0a6e229b1d4c3e0cfbab9d',
    messagingSenderId: '247344237480',
    projectId: 'play-integrity-poc-7cd08',
    storageBucket: 'play-integrity-poc-7cd08.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNZM-mIASHWDQbeRXEszWUWkcG3x4SLeg',
    appId: '1:247344237480:ios:07db2757f4c181effbab9d',
    messagingSenderId: '247344237480',
    projectId: 'play-integrity-poc-7cd08',
    storageBucket: 'play-integrity-poc-7cd08.firebasestorage.app',
    iosBundleId: 'com.nventive.internal.flutterappcheckpoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANX3fUUu7K6-dCpfLLYkKvalzHaIUQXCE',
    appId: '1:139514080243:web:019e1b6ba816e998f0c086',
    messagingSenderId: '139514080243',
    projectId: 'flutterapplicationtempla-79caa',
    authDomain: 'flutterapplicationtempla-79caa.firebaseapp.com',
    storageBucket: 'flutterapplicationtempla-79caa.appspot.com',
    measurementId: 'G-Y0TPWR6T01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFk8N8HIqLpUxi1WKPZYIYAEu4SJPEFGI',
    appId: '1:139514080243:ios:b64a363f3d032097f0c086',
    messagingSenderId: '139514080243',
    projectId: 'flutterapplicationtempla-79caa',
    storageBucket: 'flutterapplicationtempla-79caa.appspot.com',
    iosBundleId: 'com.nventive.internal.flutterappcheckpoc',
  );
}